import {ArticleData, Category, PodcastData, User} from '../../schemas/type';

const demoUser = {
  _id: 'demo-user',
  user_name: 'UltimateHealth Demo',
  user_handle: 'ultimatehealth_demo',
} as User;

export const demoCategories: Category[] = [
  {__v: 0, _id: 'demo-sleep', id: 1, name: 'Sleep'},
  {__v: 0, _id: 'demo-stress', id: 2, name: 'Stress Management'},
  {__v: 0, _id: 'demo-nutrition', id: 3, name: 'Nutrition'},
];

const demoArticleSeeds: ArticleData[] = [
  {
    _id: 'demo-article-sleep',
    title: 'Building a consistent sleep routine',
    authorName: demoUser.user_name,
    description: 'Practical habits for better rest, including a regular schedule and a calmer bedtime.',
    authorId: demoUser,
    content: '<p>A regular sleep schedule, daylight exposure, and a calm bedtime routine can improve sleep quality.</p><p>Start with one small change and keep it consistent for a week.</p>',
    summary: 'Simple, sustainable habits for improving sleep quality.',
    tags: [demoCategories[0]],
    lastUpdated: new Date().toISOString(),
    imageUtils: [],
    viewCount: 128,
    viewUsers: [],
    repostUsers: [],
    likeCount: 24,
    likedUsers: [],
    savedUsers: [],
    mentionedUsers: [],
    language: 'en-IN',
    assigned_date: null,
    discardReason: '',
    status: 'published',
    reviewer_id: null,
    contributors: [],
    pb_recordId: 'demo-record-sleep',
    difficulty: 'Beginner',
  },
  {
    _id: 'demo-article-stress',
    title: 'Simple ways to manage daily stress',
    authorName: demoUser.user_name,
    description: 'Breathing exercises, short walks, and social support are practical tools for everyday stress.',
    authorId: demoUser,
    content: '<p>Stress is easier to manage when small recovery moments are part of your day.</p><p>Try a slow breathing exercise, a short walk, or a conversation with someone you trust.</p>',
    summary: 'A practical introduction to daily stress management.',
    tags: [demoCategories[1]],
    lastUpdated: new Date().toISOString(),
    imageUtils: [],
    viewCount: 96,
    viewUsers: [],
    repostUsers: [],
    likeCount: 18,
    likedUsers: [],
    savedUsers: [],
    mentionedUsers: [],
    language: 'en-IN',
    assigned_date: null,
    discardReason: '',
    status: 'published',
    reviewer_id: null,
    contributors: [],
    pb_recordId: 'demo-record-stress',
    difficulty: 'Beginner',
  },
];

export const demoArticles: ArticleData[] = [
  ...demoArticleSeeds,
  ...[
    ['Morning movement for beginners', 'A gentle running and walking plan to make exercise feel approachable.', demoCategories[1]],
    ['Fuel your active day', 'Balanced nutrition ideas for people adding more exercise to their week.', demoCategories[2]],
    ['Running without burnout', 'Pacing, recovery, and rest-day habits for new runners.', demoCategories[1]],
    ['Hydration habits that last', 'Simple ways to remember water before, during, and after activity.', demoCategories[2]],
    ['Strength training essentials', 'A beginner-friendly introduction to safe, consistent strength work.', demoCategories[1]],
    ['Healthy technology breaks', 'Small screen-free moments that support focus, movement, and sleep.', demoCategories[0]],
    ['Mindful breathing practice', 'A short breathing routine for calmer transitions during a busy day.', demoCategories[1]],
    ['Building a balanced plate', 'Everyday nutrition guidance for colorful, satisfying meals.', demoCategories[2]],
    ['Walking for everyday health', 'How regular walking can support energy, mood, and mobility.', demoCategories[1]],
    ['Recovery after exercise', 'Rest, gentle mobility, and sleep habits that help your body recover.', demoCategories[0]],
  ].map(([title, description, category], index) => ({
    ...demoArticleSeeds[0],
    _id: `demo-article-${index + 3}`,
    title: title as string,
    description: description as string,
    summary: description as string,
    content: `<p>${description}</p><p>This local demo article is included for testing search and discovery in the browser preview.</p>`,
    tags: [category as Category],
    pb_recordId: `demo-record-${index + 3}`,
  })),
];

const demoPodcastSeeds: PodcastData[] = [
  {
    _id: 'demo-podcast-wellness',
    user_id: demoUser,
    article_id: 0,
    title: 'Wellness in five minutes',
    description: 'A short introduction to sustainable habits for sleep, stress, and nutrition.',
    audio_url: '',
    cover_image: '',
    duration: 300000,
    tags: [demoCategories[0], demoCategories[1]],
    likedUsers: [],
    savedUsers: [],
    viewUsers: [],
    viewCount: 42,
    discardReason: '',
    is_removed: false,
    mentionedUsers: [],
    reportId: null,
    status: 'published',
    admin_id: null,
    updated_at: new Date().toISOString(),
    filePath: undefined,
    downloadAt: null,
    commentCount: 0,
    language: 'en-IN',
  },
];

export const demoPodcasts: PodcastData[] = [
  ...demoPodcastSeeds,
  ...[
    ['Move more, stress less', 'Exercise and stress management'],
    ['Sleep science, simply explained', 'Sleep and recovery'],
    ['Nutrition myths unpacked', 'Nutrition and healthy habits'],
    ['A beginner running plan', 'Running and movement'],
    ['Healthy habits at work', 'Daily wellness and focus'],
    ['The recovery episode', 'Exercise and rest'],
    ['Mindfulness for busy days', 'Breathing and stress'],
    ['Walking as medicine', 'Walking and everyday health'],
    ['Building strength safely', 'Strength training'],
  ].map(([title, description], index) => ({
    ...demoPodcastSeeds[0],
    _id: `demo-podcast-${index + 2}`,
    title,
    description,
    tags: [demoCategories[index % demoCategories.length]],
  })),
];
