name: Auto Comment on PR

on:
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Add Comment to Pull Request
      uses: actions/github-script@v9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pr = context.payload.pull_request;
          const author = pr.user.login;
          const message = `Thank you @${author}, for creating the PR and contributing to our UltimateHealth project 💗.\n Our team will review the PR and will reach out to you soon! 😇\n Make sure that you have marked all the tasks that you are done with ✅.\n Thank you for your patience! 😀`;

          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr.number,
            body: message,
          });
